### PR TITLE
Create `user_files` folder for uploading files

### PR DESCRIPTION
**Pull request by asandikci**
## Problem

Problem was explained in issue https://github.com/YunoHost-Apps/overleaf_ynh/issues/11

## Solution

Created user_files 

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Known Issues
You can't still upload files bigger than 1MB

### CODE REVIEW

**Comment by asandikci** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by Thovi98** [comment]
Fixed by https://github.com/YunoHost-Apps/overleaf_ynh/pull/20

**Pull request closed without merging**
